<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Add speed_limit_cache table for persistent OSM speed limit lookups.
 */
final class Version20260317130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create speed_limit_cache table for persistent OSM speed limits';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE speed_limit_cache (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lat_rounded DOUBLE PRECISION NOT NULL, lon_rounded DOUBLE PRECISION NOT NULL, speed_limit_kmh DOUBLE PRECISION NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX speed_limit_cache_lat_lon ON speed_limit_cache (lat_rounded, lon_rounded)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE speed_limit_cache');
    }
}
