<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260301142636 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE driving_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, recorded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, latitude DOUBLE PRECISION NOT NULL, longtitude DOUBLE PRECISION NOT NULL, acceleration_x DOUBLE PRECISION NOT NULL, acceleration_y DOUBLE PRECISION NOT NULL, acceleration_z DOUBLE PRECISION NOT NULL, event_type VARCHAR(255) DEFAULT NULL, session_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A26504C6613FECDF ON driving_event (session_id)');
        $this->addSql('ALTER TABLE driving_event ADD CONSTRAINT FK_A26504C6613FECDF FOREIGN KEY (session_id) REFERENCES driving_session (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE driving_event DROP CONSTRAINT FK_A26504C6613FECDF');
        $this->addSql('DROP TABLE driving_event');
    }
}
